// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import type { OAuthProvider } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: OAuthProvider, opts?: SignInOptions) => {
      // Lovable's `~oauth` proxy only exists on Lovable preview/production hosts.
      // External deployments (for example Vercel) must start OAuth through the
      // project's Supabase endpoint or the browser is sent to a local 404 route.
      const host = typeof window === "undefined" ? "" : window.location.hostname;
      const usesLovableProxy =
        host.endsWith(".lovable.app") ||
        host.endsWith(".lovableproject.com") ||
        host.endsWith(".lovableproject-dev.com");

      if (!usesLovableProxy) {
        const { data, error } = await supabase.auth.signInWithOAuth({
          provider: provider as Parameters<typeof supabase.auth.signInWithOAuth>[0]["provider"],
          options: {
            redirectTo: opts?.redirect_uri ?? window.location.origin,
            ...(opts?.extraParams ? { queryParams: opts.extraParams } : {}),
          },
        });

        return { redirected: Boolean(data.url), error, url: data.url };
      }

      const result = await lovableAuth.signInWithOAuth(provider, {
        ...opts,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
