REVOKE EXECUTE ON FUNCTION public.admin_notification_history(integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_overview() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_push_stats() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_push_subscribers(integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_set_role(uuid, public.app_role) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_users(integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.advance_chapter_learning_state() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.auto_schedule_targets() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.close_stale_sessions() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.complete_matching_daily_plan() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.log_reading(text, integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.refresh_all_daily_study_plans() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.touch_last_seen() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.undo_reading(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.user_local_date(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.update_study_streak() FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.admin_notification_history(integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.admin_overview() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.admin_push_stats() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.admin_push_subscribers(integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.admin_set_role(uuid, public.app_role) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.admin_users(integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.auto_schedule_targets() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.log_reading(text, integer) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.touch_last_seen() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.undo_reading(text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.user_local_date(uuid) TO authenticated, service_role;